###
POST http://localhost:3000/api/sign-in
Content-Type: application/json

{

}

###Example of missing password
POST http://localhost:3000/api/sign-in
Content-Type: application/json

{
 "email":"a@b.com"
}


###Example of bad email
POST http://localhost:3000/api/sign-in
Content-Type: application/json

{
 "email":"a.com",
 "password":"1234"
}

###Example postive validated values
POST http://localhost:3000/api/sign-in
Content-Type: application/json

{
 "email":"a@b.com",
 "password":"1234"
}
